CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    password_reset_token VARCHAR(255),
    reset_token_expiry TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT chk_users_role CHECK (role IN ('CLIENT', 'PROVIDER', 'ADMIN'))
);

CREATE TABLE IF NOT EXISTS skill_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    icon VARCHAR(255),
    description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS provider_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    bio VARCHAR(2000),
    avatar_url VARCHAR(255),
    city VARCHAR(255),
    avg_rating DOUBLE PRECISION NOT NULL DEFAULT 0,
    total_reviews INTEGER NOT NULL DEFAULT 0,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    phone_number VARCHAR(255),
    profile_complete BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_provider_profiles_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS client_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    phone_number VARCHAR(255),
    avatar_url VARCHAR(255),
    CONSTRAINT fk_client_profiles_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS provider_skills (
    provider_id BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,
    PRIMARY KEY (provider_id, skill_id),
    CONSTRAINT fk_provider_skills_provider FOREIGN KEY (provider_id) REFERENCES provider_profiles(id),
    CONSTRAINT fk_provider_skills_skill FOREIGN KEY (skill_id) REFERENCES skill_categories(id)
);

CREATE TABLE IF NOT EXISTS provider_portfolio_links (
    provider_id BIGINT NOT NULL,
    link_url VARCHAR(2048) NOT NULL,
    PRIMARY KEY (provider_id, link_url),
    CONSTRAINT fk_provider_portfolio_links_provider FOREIGN KEY (provider_id) REFERENCES provider_profiles(id)
);

CREATE TABLE IF NOT EXISTS addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_profile_id BIGINT NOT NULL,
    label VARCHAR(255),
    street_address VARCHAR(255) NOT NULL,
    city VARCHAR(255),
    area VARCHAR(255),
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_addresses_client_profile FOREIGN KEY (client_profile_id) REFERENCES client_profiles(id)
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    preferred_date DATE NOT NULL,
    preferred_time TIME NOT NULL,
    job_description VARCHAR(1000) NOT NULL,
    status VARCHAR(20) NOT NULL,
    decline_reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_bookings_client FOREIGN KEY (client_id) REFERENCES users(id),
    CONSTRAINT fk_bookings_provider FOREIGN KEY (provider_id) REFERENCES provider_profiles(id),
    CONSTRAINT chk_bookings_status CHECK (status IN ('PENDING', 'ACCEPTED', 'DECLINED', 'PAID', 'COMPLETED', 'CANCELLED'))
);

CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL UNIQUE,
    client_id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    rating INTEGER NOT NULL,
    comment VARCHAR(1000) NOT NULL,
    provider_response VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    responded_at TIMESTAMP,
    CONSTRAINT fk_reviews_booking FOREIGN KEY (booking_id) REFERENCES bookings(id),
    CONSTRAINT fk_reviews_client FOREIGN KEY (client_id) REFERENCES users(id),
    CONSTRAINT fk_reviews_provider FOREIGN KEY (provider_id) REFERENCES provider_profiles(id),
    CONSTRAINT chk_reviews_rating CHECK (rating BETWEEN 1 AND 5)
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    content VARCHAR(2000) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    sent_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_messages_booking FOREIGN KEY (booking_id) REFERENCES bookings(id),
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL UNIQUE,
    client_id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    platform_fee NUMERIC(10, 2) NOT NULL,
    provider_earnings NUMERIC(10, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    payment_method VARCHAR(255) NOT NULL,
    payment_token VARCHAR(255),
    transaction_ref VARCHAR(255) UNIQUE,
    paid_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_payments_booking FOREIGN KEY (booking_id) REFERENCES bookings(id),
    CONSTRAINT fk_payments_client FOREIGN KEY (client_id) REFERENCES users(id),
    CONSTRAINT fk_payments_provider FOREIGN KEY (provider_id) REFERENCES users(id),
    CONSTRAINT chk_payments_status CHECK (status IN ('PENDING', 'COMPLETED', 'REFUNDED'))
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    message VARCHAR(500) NOT NULL,
    type VARCHAR(255) NOT NULL,
    reference_id BIGINT,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT NOT NULL,
    action VARCHAR(255) NOT NULL,
    target_type VARCHAR(255) NOT NULL,
    target_id BIGINT NOT NULL,
    details VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_audit_logs_admin FOREIGN KEY (admin_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_bookings_client_id ON bookings (client_id);
CREATE INDEX IF NOT EXISTS idx_bookings_provider_id ON bookings (provider_id);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings (status);
CREATE INDEX IF NOT EXISTS idx_reviews_provider_id ON reviews (provider_id);
CREATE INDEX IF NOT EXISTS idx_messages_booking_sent_at ON messages (booking_id, sent_at);
CREATE INDEX IF NOT EXISTS idx_payments_provider_status ON payments (provider_id, status);
CREATE INDEX IF NOT EXISTS idx_notifications_recipient_read ON notifications (recipient_id, is_read);
CREATE INDEX IF NOT EXISTS idx_audit_logs_admin_created_at ON audit_logs (admin_id, created_at);
