CREATE TABLE IF NOT EXISTS job_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    budget NUMERIC(10, 2) NOT NULL,
    location VARCHAR(255),
    deadline DATE,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_job_posts_client FOREIGN KEY (client_id) REFERENCES users(id),
    CONSTRAINT fk_job_posts_category FOREIGN KEY (category_id) REFERENCES skill_categories(id),
    CONSTRAINT chk_job_posts_status CHECK (status IN ('OPEN', 'FILLED', 'CLOSED'))
);

CREATE TABLE IF NOT EXISTS proposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_post_id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    booking_id BIGINT,
    cover_message VARCHAR(2000) NOT NULL,
    proposed_price NUMERIC(10, 2) NOT NULL,
    estimated_delivery_time VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_proposals_job_post FOREIGN KEY (job_post_id) REFERENCES job_posts(id),
    CONSTRAINT fk_proposals_provider FOREIGN KEY (provider_id) REFERENCES provider_profiles(id),
    CONSTRAINT fk_proposals_booking FOREIGN KEY (booking_id) REFERENCES bookings(id),
    CONSTRAINT uq_proposals_job_provider UNIQUE (job_post_id, provider_id),
    CONSTRAINT chk_proposals_status CHECK (status IN ('PENDING', 'ACCEPTED', 'DECLINED'))
);

CREATE INDEX IF NOT EXISTS idx_job_posts_status_created ON job_posts (status, created_at);
CREATE INDEX IF NOT EXISTS idx_job_posts_client ON job_posts (client_id);
CREATE INDEX IF NOT EXISTS idx_proposals_job_post ON proposals (job_post_id);
CREATE INDEX IF NOT EXISTS idx_proposals_provider ON proposals (provider_id);
