import { Platform, StyleSheet } from 'react-native';

const fontFamily = Platform.select({
  web: '"Manrope", "SF Pro Display", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  ios: 'System',
  android: 'Roboto',
  default: 'System',
});

export const typography = StyleSheet.create({
  h1: {
    fontFamily,
    fontSize: 48,
    fontWeight: '800',
    lineHeight: 58,
    letterSpacing: 0,
  },
  h2: {
    fontFamily,
    fontSize: 36,
    fontWeight: '700',
    lineHeight: 47,
    letterSpacing: 0,
  },
  h3: {
    fontFamily,
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 34,
    letterSpacing: 0,
  },
  h4: {
    fontFamily,
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 28,
    letterSpacing: 0,
  },
  bodyLg: {
    fontFamily,
    fontSize: 18,
    fontWeight: '400',
    lineHeight: 29,
    letterSpacing: 0,
  },
  body: {
    fontFamily,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 24,
    letterSpacing: 0,
  },
  bodyMedium: {
    fontFamily,
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 24,
    letterSpacing: 0,
  },
  small: {
    fontFamily,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
    letterSpacing: 0,
  },
  smallMedium: {
    fontFamily,
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
    letterSpacing: 0,
  },
  caption: {
    fontFamily,
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 17,
    letterSpacing: 0,
  },
  captionMedium: {
    fontFamily,
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 17,
    letterSpacing: 0,
  },
  label: {
    fontFamily,
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 14,
    letterSpacing: 0.7,
  },
  button: {
    fontFamily,
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 14,
    letterSpacing: 0.7,
  },
  buttonSmall: {
    fontFamily,
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 12,
    letterSpacing: 0.4,
  },
  navLabel: {
    fontFamily,
    fontSize: 10,
    fontWeight: '500',
    lineHeight: 12,
    letterSpacing: 0,
  },
});
